// site.go generates a multi-page static site similar to GitBook.
// It includes sidebar navigation, previous/next links, search, and responsive layout.
package output

import (
	"encoding/json"
	"fmt"
	"html/template"
	"os"
	"path/filepath"
	"strings"
	"unicode/utf8"

	"github.com/yeasy/mdpress/pkg/utils"
)

const (
	// maxSearchTextLength limits how much text is included per page in the search index.
	maxSearchTextLength = 50000
	// searchSnippetExtraRunes is the number of runes after a heading title to include in the search snippet.
	searchSnippetExtraRunes = 500
)

// SiteChapter stores rendered chapter data for site output.
type SiteChapter struct {
	Title    string
	ID       string
	Filename string // Output HTML filename, for example "ch01.html".
	Content  string // Rendered HTML content.
	Markdown string // Source markdown after variable expansion.
	Depth    int
	Headings []SiteNavHeading
	Children []SiteChapter
}

// SiteNavHeading stores an in-chapter navigation tree.
type SiteNavHeading struct {
	Title    string
	ID       string
	Children []SiteNavHeading
}

// SiteMeta stores site-wide metadata.
type SiteMeta struct {
	Title            string
	Subtitle         string
	Description      string
	Author           string
	Language         string
	Theme            string // CSS theme name.
	ThemeDescription string
}

// SiteGenerator generates the static site.
type SiteGenerator struct {
	Meta     SiteMeta
	Chapters []SiteChapter
	CSS      string // Theme CSS plus custom CSS.
}

// NewSiteGenerator creates a site generator.
func NewSiteGenerator(meta SiteMeta) *SiteGenerator {
	return &SiteGenerator{Meta: meta}
}

// validateFilename ensures that filename does not escape outputDir via path traversal.
// It rejects absolute paths and paths containing ".." to prevent writing outside the
// intended output directory. This is critical when filenames come from user-controlled
// sources such as SUMMARY.md chapter paths.
func validateFilename(outputDir, filename string) error {
	// Reject absolute paths
	if filepath.IsAbs(filename) {
		return fmt.Errorf("filename must be relative, not absolute: %q", filename)
	}

	// Reject paths containing ".."
	if strings.Contains(filename, "..") {
		return fmt.Errorf("filename must not contain '..': %q", filename)
	}

	// Clean the filename and verify it doesn't escape outputDir
	cleaned := filepath.Clean(filename)
	fullPath := filepath.Join(outputDir, cleaned)

	// Convert to absolute paths for reliable comparison
	absOutputDir, err := filepath.Abs(outputDir)
	if err != nil {
		return fmt.Errorf("failed to resolve output directory: %w", err)
	}
	absFullPath, err := filepath.Abs(fullPath)
	if err != nil {
		return fmt.Errorf("failed to resolve file path: %w", err)
	}

	// Ensure the resolved path is within outputDir
	if !strings.HasPrefix(absFullPath, absOutputDir+string(filepath.Separator)) &&
		absFullPath != absOutputDir {
		return fmt.Errorf("filename escapes output directory: %q", filename)
	}

	return nil
}

// AddChapter appends a chapter.
func (g *SiteGenerator) AddChapter(ch SiteChapter) {
	g.Chapters = append(g.Chapters, ch)
}

// SetCSS sets the site CSS, sanitizing it to prevent style-tag breakout.
func (g *SiteGenerator) SetCSS(css string) {
	g.CSS = utils.SanitizeCSS(css)
}

// Generate generates the static site pages, sitemap, and search index.
func (g *SiteGenerator) Generate(outputDir string) error {
	if err := utils.EnsureDir(outputDir); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	// Flatten nested chapters for previous/next navigation.
	flatPages := g.flattenChapters(g.Chapters)

	// Assign filenames to pages that do not already have one.
	for i := range flatPages {
		if flatPages[i].Filename == "" {
			flatPages[i].Filename = fmt.Sprintf("page_%d.html", i)
		}
		// Validate filename to prevent path traversal attacks
		if err := validateFilename(outputDir, flatPages[i].Filename); err != nil {
			return fmt.Errorf("invalid filename for page %d: %w", i, err)
		}
	}

	// Parse the page template.
	// SECURITY: safeHTML and safeCSS functions bypass the template escaper and must only be
	// called with internally-generated content. Currently used for:
	// - SidebarHTML: generated by buildSidebar() (trusted)
	// - Content: rendered Markdown output (trusted, never raw user input from forms/URLs)
	// DO NOT pass untrusted data through these functions; doing so creates XSS vulnerabilities.
	tmpl, err := template.New("page").Funcs(template.FuncMap{
		"safeHTML": func(s string) template.HTML { return template.HTML(s) },
		"safeCSS":  func(s string) template.CSS { return template.CSS(s) },
	}).Parse(sitePageTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse page template: %w", err)
	}

	// Render every page.
	for i, page := range flatPages {
		var prevLink, nextLink, prevTitle, nextTitle string
		if i > 0 {
			prevLink = flatPages[i-1].Filename
			prevTitle = flatPages[i-1].Title
		}
		if i < len(flatPages)-1 {
			nextLink = flatPages[i+1].Filename
			nextTitle = flatPages[i+1].Title
		}

		sidebarHTML := g.buildSidebar(g.Chapters, page.Filename)
		data := pageData{
			SiteTitle:        g.Meta.Title,
			SiteSubtitle:     g.Meta.Subtitle,
			SiteDescription:  g.Meta.Description,
			Author:           g.Meta.Author,
			Language:         g.Meta.Language,
			ThemeName:        g.Meta.Theme,
			ThemeDescription: g.Meta.ThemeDescription,
			PageTitle:        page.Title,
			Description:      extractDescription(page.Content),
			Breadcrumbs:      resolveBreadcrumbs(g.buildBreadcrumbs(g.Chapters, page.Filename)),
			Content:          page.Content,
			CSS:              g.CSS,
			SidebarHTML:      sidebarHTML,
			HomeLink:         absoluteSiteHref("index.html"),
			SitemapLink:      absoluteSiteHref("sitemap.xml"),
			PrevLink:         absoluteSiteHref(prevLink),
			PrevTitle:        prevTitle,
			NextLink:         absoluteSiteHref(nextLink),
			NextTitle:        nextTitle,
			ActiveFile:       page.Filename,
			TotalPages:       len(flatPages),
			CurrentPage:      i + 1,
			ShowTitle:        !contentStartsWithTitle(page.Content, page.Title),
		}
		populateUIStrings(&data)

		var buf strings.Builder
		if err := tmpl.Execute(&buf, data); err != nil {
			return fmt.Errorf("failed to render page %s: %w", page.Filename, err)
		}

		outPath := filepath.Join(outputDir, page.Filename)
		if err := utils.EnsureDir(filepath.Dir(outPath)); err != nil {
			return fmt.Errorf("failed to create page directory for %s: %w", page.Filename, err)
		}
		if err := os.WriteFile(outPath, []byte(buf.String()), 0o644); err != nil {
			return fmt.Errorf("failed to write %s: %w", page.Filename, err)
		}

	}

	// Generate index.html as a full first-chapter page so the SPA loads instantly
	// at the site root without an HTTP redirect flicker.  The SPA router takes
	// over from there for subsequent navigation.
	var indexHTML string
	if len(flatPages) > 0 {
		firstPage := flatPages[0]
		// index.html shows the first chapter content with the sidebar active on
		// that chapter.  The "previous" nav link is omitted; "next" points to
		// the second page when it exists.
		var nextLink, nextTitle string
		if len(flatPages) > 1 {
			nextLink = flatPages[1].Filename
			nextTitle = flatPages[1].Title
		}
		idxData := pageData{
			SiteTitle:        g.Meta.Title,
			SiteSubtitle:     g.Meta.Subtitle,
			SiteDescription:  g.Meta.Description,
			Author:           g.Meta.Author,
			Language:         g.Meta.Language,
			ThemeName:        g.Meta.Theme,
			ThemeDescription: g.Meta.ThemeDescription,
			PageTitle:        firstPage.Title,
			Description:      firstNonEmpty(g.Meta.Description, extractDescription(firstPage.Content)),
			Breadcrumbs:      nil,
			Content:          firstPage.Content,
			CSS:              g.CSS,
			SidebarHTML:      g.buildSidebar(g.Chapters, "index.html"),
			HomeLink:         "/index.html",
			SitemapLink:      "/sitemap.xml",
			NextLink:         absoluteSiteHref(nextLink),
			NextTitle:        nextTitle,
			ActiveFile:       "index.html",
			TotalPages:       len(flatPages),
			CurrentPage:      1,
			ShowTitle:        !contentStartsWithTitle(firstPage.Content, firstPage.Title),
		}
		populateUIStrings(&idxData)
		var buf strings.Builder
		if err := tmpl.Execute(&buf, idxData); err != nil {
			return fmt.Errorf("failed to render index.html: %w", err)
		}
		indexHTML = buf.String()
	} else {
		indexHTML = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>` +
			template.HTMLEscapeString(g.Meta.Title) +
			`</title></head><body><p>No chapters available.</p></body></html>`
	}
	if err := os.WriteFile(filepath.Join(outputDir, "index.html"), []byte(indexHTML), 0o644); err != nil {
		return fmt.Errorf("failed to write index.html: %w", err)
	}
	// Generate sitemap.xml for search engine indexing.
	if len(flatPages) > 0 {
		var sm strings.Builder
		sm.WriteString(`<?xml version="1.0" encoding="UTF-8"?>` + "\n")
		sm.WriteString(`<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">` + "\n")
		sm.WriteString("  <url><loc>index.html</loc><priority>1.0</priority></url>\n")
		for _, page := range flatPages {
			fmt.Fprintf(&sm, "  <url><loc>%s</loc></url>\n", template.HTMLEscapeString(page.Filename))
		}
		sm.WriteString("</urlset>\n")
		if err := os.WriteFile(filepath.Join(outputDir, "sitemap.xml"), []byte(sm.String()), 0o644); err != nil {
			return fmt.Errorf("failed to write sitemap.xml: %w", err)
		}
	}

	// Generate search-index.json for client-side full-text search.
	if len(flatPages) > 0 {
		entries := make([]searchEntry, 0, len(flatPages))
		for _, page := range flatPages {
			plainText := htmlTagPattern.ReplaceAllString(page.Content, " ")
			plainText = strings.Join(strings.Fields(plainText), " ")
			if utf8.RuneCountInString(plainText) > maxSearchTextLength {
				plainText = string([]rune(plainText)[:maxSearchTextLength])
			}
			crumbs := g.buildBreadcrumbs(g.Chapters, page.Filename)
			var pathParts []string
			for _, c := range crumbs {
				if c.Filename != page.Filename {
					pathParts = append(pathParts, c.Title)
				}
			}
			pathStr := strings.Join(pathParts, " > ")
			entries = append(entries, searchEntry{
				Title:    page.Title,
				Filename: page.Filename,
				Text:     plainText,
				Path:     pathStr,
			})
			entries = append(entries, searchEntriesForHeadings(page, plainText)...)
		}
		indexJSON, err := json.Marshal(entries)
		if err != nil {
			return fmt.Errorf("failed to marshal search index: %w", err)
		}
		if err := os.WriteFile(filepath.Join(outputDir, "search-index.json"), indexJSON, 0o644); err != nil {
			return fmt.Errorf("failed to write search-index.json: %w", err)
		}
	}
	return nil
}

// flattenChapters expands nested chapters into a flat list.
func (g *SiteGenerator) flattenChapters(chapters []SiteChapter) []SiteChapter {
	var result []SiteChapter
	for _, ch := range chapters {
		flat := ch
		flat.Children = nil
		result = append(result, flat)
		if len(ch.Children) > 0 {
			result = append(result, g.flattenChapters(ch.Children)...)
		}
	}
	return result
}

// breadcrumb represents a navigation breadcrumb segment, containing the title
// and filename for one level in the breadcrumb trail.
type breadcrumb struct {
	Title    string
	Filename string
}

// pageData contains all the information needed to render a single page of the site,
// including site metadata, page content, navigation elements, and styling.
type pageData struct {
	SiteTitle        string
	SiteSubtitle     string
	SiteDescription  string
	Author           string
	Language         string
	ThemeName        string
	ThemeDescription string
	PageTitle        string
	Description      string // First ~160 chars of plain text for meta description.
	Breadcrumbs      []breadcrumb
	Content          string
	CSS              string
	SidebarHTML      string
	HomeLink         string
	SitemapLink      string
	PrevLink         string
	PrevTitle        string
	NextLink         string
	NextTitle        string
	ActiveFile       string
	TotalPages       int
	CurrentPage      int
	ShowTitle        bool // true when Content lacks an <h1>, so the template should insert one.

	// Localized UI strings.
	UIprevious          string
	UInext              string
	UIsearchPlaceholder string
	UIsearchButton      string
	UInoResults         string
	UIsearchUnavailable string
	UIsearchResultsOne  string
	UIsearchResults     string
	UIrecentPages       string
	UIrecentEmpty       string
	UIsearchNavigate    string
	UIsearchOpen        string
	UIsearchClose       string
	UIsearchMatchTitle  string
	UIsearchMatchPath   string
	UIsearchMatchText   string
	UIsearchMatched     string
	UIonThisPage        string
	UIcopy              string
	UIcopied            string
	UIhideSidebar       string
	UIlightMode         string
	UIdarkMode          string
	UIsystemDefault     string
	UIsearchKbd         string
	UIpageOf            string
	UIbuiltWith         string
}

type searchEntry struct {
	Title    string `json:"t"`
	Filename string `json:"f"`
	Text     string `json:"x"`
	Path     string `json:"p"`
}

func searchEntriesForHeadings(page SiteChapter, plainText string) []searchEntry {
	entries := make([]searchEntry, 0)
	// Convert to rune slice once for safe UTF-8 slicing across all headings.
	runeText := []rune(plainText)
	var walk func([]SiteNavHeading)
	walk = func(items []SiteNavHeading) {
		for _, item := range items {
			if item.ID != "" {
				// Include only a short snippet around the heading to avoid
				// duplicating the entire page text for every heading entry.
				snippet := item.Title
				if idx := strings.Index(plainText, item.Title); idx >= 0 {
					runeIdx := utf8.RuneCountInString(plainText[:idx])
					end := runeIdx + utf8.RuneCountInString(item.Title) + searchSnippetExtraRunes
					if end > len(runeText) {
						end = len(runeText)
					}
					snippet = string(runeText[runeIdx:end])
				}
				entries = append(entries, searchEntry{
					Title:    item.Title,
					Filename: page.Filename + "#" + item.ID,
					Text:     snippet,
					Path:     page.Title,
				})
			}
			walk(item.Children)
		}
	}
	walk(page.Headings)
	return entries
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if strings.TrimSpace(value) != "" {
			return value
		}
	}
	return ""
}

func absoluteSiteHref(target string) string {
	if target == "" {
		return ""
	}
	// Use absolute paths (rooted with "/") so that links remain correct after
	// SPA client-side navigation changes the browser URL.  Relative paths
	// break because the sidebar HTML is not re-rendered during SPA page swaps,
	// and the browser resolves relative hrefs against the new (changed) URL.
	return "/" + filepath.ToSlash(filepath.Clean(target))
}

func resolveBreadcrumbs(crumbs []breadcrumb) []breadcrumb {
	if len(crumbs) == 0 {
		return nil
	}
	out := make([]breadcrumb, len(crumbs))
	for i, crumb := range crumbs {
		out[i] = breadcrumb{
			Title:    crumb.Title,
			Filename: absoluteSiteHref(crumb.Filename),
		}
	}
	return out
}
