package cmd

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestGeneratePreviewHTML_Basic tests basic HTML generation for themes preview
func TestGeneratePreviewHTML_Basic(t *testing.T) {
	themes := []Theme{
		{
			Name:        "test",
			DisplayName: "Test Theme",
			Description: "A test theme",
			Author:      "Test Author",
			Version:     "1.0.0",
			Colors: ThemeColors{
				Primary:    "#FF0000",
				Secondary:  "#00FF00",
				Accent:     "#0000FF",
				Text:       "#000000",
				Background: "#FFFFFF",
				CodeBg:     "#F0F0F0",
			},
		},
	}

	result := generatePreviewHTML(themes)

	// Verify HTML structure
	checks := []struct {
		name    string
		content string
	}{
		{"doctype", "<!DOCTYPE html>"},
		{"html lang", `<html lang="en">`},
		{"charset", `<meta charset="UTF-8">`},
		{"title", "<title>mdpress Themes Preview</title>"},
		{"header", "mdpress Theme Showcase"},
		{"container div", `<div class="container">`},
		{"themes grid", `<div class="themes-grid">`},
		{"footer", "Generated by mdpress"},
		{"closing html", "</html>"},
	}

	for _, check := range checks {
		if !strings.Contains(result, check.content) {
			t.Errorf("generatePreviewHTML() should contain %q, got output: %s", check.name, result[:200])
		}
	}
}

// TestGeneratePreviewHTML_EmptyThemes tests with no themes
func TestGeneratePreviewHTML_EmptyThemes(t *testing.T) {
	result := generatePreviewHTML([]Theme{})

	// Should still generate valid HTML structure
	if !strings.Contains(result, "<!DOCTYPE html>") {
		t.Error("generatePreviewHTML() should generate doctype even with empty themes")
	}
	if !strings.Contains(result, "mdpress Theme Showcase") {
		t.Error("generatePreviewHTML() should generate header even with empty themes")
	}
	if !strings.Contains(result, "</html>") {
		t.Error("generatePreviewHTML() should have closing html tag")
	}
}

// TestGeneratePreviewHTML_MultipleThemes tests with multiple themes
func TestGeneratePreviewHTML_MultipleThemes(t *testing.T) {
	themes := []Theme{
		{
			Name:        "tech",
			DisplayName: "Technical",
			Description: "Technical theme",
			Author:      "Author1",
			Version:     "1.0.0",
			Colors: ThemeColors{
				Primary:    "#1A5490",
				Secondary:  "#0066CC",
				Accent:     "#0066CC",
				Text:       "#2C3E50",
				Background: "#FFFFFF",
				CodeBg:     "#F5F7F9",
			},
		},
		{
			Name:        "elegant",
			DisplayName: "Elegant",
			Description: "Elegant theme",
			Author:      "Author2",
			Version:     "1.0.0",
			Colors: ThemeColors{
				Primary:    "#34495e",
				Secondary:  "#16a085",
				Accent:     "#d35400",
				Text:       "#2c3e50",
				Background: "#ecf0f1",
				CodeBg:     "#e8e8e8",
			},
		},
	}

	result := generatePreviewHTML(themes)

	// Should contain both theme sections
	if !strings.Contains(result, "Technical") {
		t.Error("generatePreviewHTML() should contain first theme name")
	}
	if !strings.Contains(result, "Elegant") {
		t.Error("generatePreviewHTML() should contain second theme name")
	}
}

// TestGeneratePreviewHTML_ContainsStyles tests that CSS styles are present
func TestGeneratePreviewHTML_ContainsStyles(t *testing.T) {
	themes := []Theme{}
	result := generatePreviewHTML(themes)

	styleChecks := []string{
		"<style>",
		"</style>",
		"body {",
		"font-family:",
		"background:",
		".container {",
		".themes-grid {",
		".theme-section {",
		"@media",
	}

	for _, check := range styleChecks {
		if !strings.Contains(result, check) {
			t.Errorf("generatePreviewHTML() should contain CSS %q", check)
		}
	}
}

// TestGeneratePreviewHTML_ValidHTML tests that generated HTML is well-formed
func TestGeneratePreviewHTML_ValidHTML(t *testing.T) {
	themes := []Theme{
		{
			Name:        "test",
			DisplayName: "Test",
			Description: "Desc",
			Author:      "Auth",
			Version:     "1.0",
			Colors: ThemeColors{
				Primary:    "#111111",
				Secondary:  "#222222",
				Accent:     "#333333",
				Text:       "#000000",
				Background: "#FFFFFF",
				CodeBg:     "#F0F0F0",
			},
		},
	}

	result := generatePreviewHTML(themes)

	// Check opening and closing tags match
	htmlOpen := strings.Count(result, "<html")
	htmlClose := strings.Count(result, "</html>")
	if htmlOpen != htmlClose {
		t.Error("generatePreviewHTML() html tags should match")
	}

	bodyOpen := strings.Count(result, "<body")
	bodyClose := strings.Count(result, "</body>")
	if bodyOpen != bodyClose {
		t.Error("generatePreviewHTML() body tags should match")
	}

	headOpen := strings.Count(result, "<head")
	headClose := strings.Count(result, "</head>")
	if headOpen != headClose {
		t.Error("generatePreviewHTML() head tags should match")
	}
}

// TestGenerateThemePreviewSection_Basic tests single theme section generation
func TestGenerateThemePreviewSection_Basic(t *testing.T) {
	theme := Theme{
		Name:        "test",
		DisplayName: "Test Theme",
		Description: "Test Description",
		Author:      "Test Author",
		Version:     "1.0.0",
		Colors: ThemeColors{
			Primary:    "#FF0000",
			Secondary:  "#00FF00",
			Accent:     "#0000FF",
			Text:       "#000000",
			Background: "#FFFFFF",
			CodeBg:     "#F0F0F0",
		},
	}

	result := generateThemePreviewSection(theme)

	// Verify structure
	if !strings.Contains(result, "theme-section") {
		t.Error("generateThemePreviewSection() should contain theme-section class")
	}
	if !strings.Contains(result, "Test Theme") {
		t.Error("generateThemePreviewSection() should contain display name")
	}
	if !strings.Contains(result, "test") {
		t.Error("generateThemePreviewSection() should contain theme name")
	}
}

// TestGenerateThemePreviewSection_ContainsColors tests color display
func TestGenerateThemePreviewSection_ContainsColors(t *testing.T) {
	theme := Theme{
		Name:        "colortest",
		DisplayName: "Color Test",
		Description: "Testing colors",
		Author:      "Tester",
		Version:     "1.0.0",
		Colors: ThemeColors{
			Primary:    "#123456",
			Secondary:  "#ABCDEF",
			Accent:     "#FEDCBA",
			Text:       "#111111",
			Background: "#EEEEEE",
			CodeBg:     "#DDDDDD",
		},
	}

	result := generateThemePreviewSection(theme)

	// Verify all colors are included
	colorChecks := []string{
		"#123456", // Primary
		"#ABCDEF", // Secondary
		"#FEDCBA", // Accent
		"#111111", // Text
		"#EEEEEE", // Background
		"#DDDDDD", // CodeBg
		"color-swatch",
		"Primary",
		"Secondary",
		"Accent",
	}

	for _, check := range colorChecks {
		if !strings.Contains(result, check) {
			t.Errorf("generateThemePreviewSection() should contain %q", check)
		}
	}
}

// TestGenerateThemePreviewSection_ContainsSampleContent tests sample content sections
func TestGenerateThemePreviewSection_ContainsSampleContent(t *testing.T) {
	theme := Theme{
		Name:        "content",
		DisplayName: "Content Test",
		Description: "Testing content",
		Author:      "Tester",
		Version:     "1.0.0",
		Colors: ThemeColors{
			Primary:    "#000000",
			Secondary:  "#111111",
			Accent:     "#222222",
			Text:       "#333333",
			Background: "#FFFFFF",
			CodeBg:     "#F0F0F0",
		},
	}

	result := generateThemePreviewSection(theme)

	// Verify sample content
	contentChecks := []string{
		"Sample Heading",
		"sample paragraph",
		"inline code",
		"Sample code block",
		"func greet",
		"<table",
		"<thead",
		"<tbody",
		"Feature",
		"Value",
		"blockquote",
	}

	for _, check := range contentChecks {
		if !strings.Contains(result, check) {
			t.Errorf("generateThemePreviewSection() should contain %q", check)
		}
	}
}

// TestGenerateThemePreviewSection_MetadataDisplay tests theme metadata
func TestGenerateThemePreviewSection_MetadataDisplay(t *testing.T) {
	theme := Theme{
		Name:        "metadata",
		DisplayName: "Metadata Test",
		Description: "For testing metadata",
		Author:      "John Doe",
		Version:     "2.5.3",
		Colors: ThemeColors{
			Primary:    "#000000",
			Secondary:  "#111111",
			Accent:     "#222222",
			Text:       "#333333",
			Background: "#FFFFFF",
			CodeBg:     "#F0F0F0",
		},
	}

	result := generateThemePreviewSection(theme)

	// Verify metadata is displayed
	if !strings.Contains(result, "John Doe") {
		t.Error("generateThemePreviewSection() should contain author")
	}
	if !strings.Contains(result, "2.5.3") {
		t.Error("generateThemePreviewSection() should contain version")
	}
	if !strings.Contains(result, "For testing metadata") {
		t.Error("generateThemePreviewSection() should contain description")
	}
}

// TestExecuteThemesPreview_DefaultPath tests preview generation with default path
func TestExecuteThemesPreview_DefaultPath(t *testing.T) {
	tmpDir := t.TempDir()
	originalDir, err := os.Getwd()
	if err != nil {
		t.Fatalf("failed to get current directory: %v", err)
	}

	if err := os.Chdir(tmpDir); err != nil {
		t.Fatalf("failed to change directory: %v", err)
	}
	defer func() { _ = os.Chdir(originalDir) }()

	err = executeThemesPreview("")
	if err != nil {
		t.Fatalf("executeThemesPreview(\"\") returned error: %v", err)
	}

	// Verify file was created with default name
	if _, err := os.Stat("themes-preview.html"); os.IsNotExist(err) {
		t.Error("executeThemesPreview(\"\") should create themes-preview.html")
	}
}

// TestExecuteThemesPreview_CustomPath tests preview generation with custom path
func TestExecuteThemesPreview_CustomPath(t *testing.T) {
	tmpDir := t.TempDir()
	customPath := filepath.Join(tmpDir, "custom-preview.html")

	err := executeThemesPreview(customPath)
	if err != nil {
		t.Fatalf("executeThemesPreview with custom path returned error: %v", err)
	}

	// Verify file was created at custom path
	if _, err := os.Stat(customPath); os.IsNotExist(err) {
		t.Errorf("executeThemesPreview(%q) should create file at custom path", customPath)
	}
}

// TestExecuteThemesPreview_CreatesValidHTML tests that generated file contains valid HTML
func TestExecuteThemesPreview_CreatesValidHTML(t *testing.T) {
	tmpDir := t.TempDir()
	filePath := filepath.Join(tmpDir, "test-preview.html")

	err := executeThemesPreview(filePath)
	if err != nil {
		t.Fatalf("executeThemesPreview returned error: %v", err)
	}

	// Read the generated file
	content, err := os.ReadFile(filePath)
	if err != nil {
		t.Fatalf("failed to read generated file: %v", err)
	}

	contentStr := string(content)

	// Verify it contains valid HTML
	if !strings.Contains(contentStr, "<!DOCTYPE html>") {
		t.Error("generated file should contain DOCTYPE")
	}
	if !strings.Contains(contentStr, "mdpress Theme Showcase") {
		t.Error("generated file should contain theme showcase header")
	}
	if !strings.Contains(contentStr, "</html>") {
		t.Error("generated file should have closing html tag")
	}
}

// TestExecuteThemesPreview_FilePermissions tests that generated file has correct permissions
func TestExecuteThemesPreview_FilePermissions(t *testing.T) {
	tmpDir := t.TempDir()
	filePath := filepath.Join(tmpDir, "perm-test.html")

	err := executeThemesPreview(filePath)
	if err != nil {
		t.Fatalf("executeThemesPreview returned error: %v", err)
	}

	// Check file exists and is readable
	info, err := os.Stat(filePath)
	if err != nil {
		t.Fatalf("failed to stat generated file: %v", err)
	}

	if !info.Mode().IsRegular() {
		t.Error("generated file should be a regular file")
	}

	// Verify we can read the file
	_, err = os.ReadFile(filePath)
	if err != nil {
		t.Errorf("should be able to read generated file: %v", err)
	}
}

// TestExecuteThemesPreview_AbsolutePath tests with absolute path
func TestExecuteThemesPreview_AbsolutePath(t *testing.T) {
	tmpDir := t.TempDir()
	absPath := filepath.Join(tmpDir, "absolute-preview.html")

	err := executeThemesPreview(absPath)
	if err != nil {
		t.Fatalf("executeThemesPreview with absolute path returned error: %v", err)
	}

	// Verify file was created
	if _, err := os.Stat(absPath); os.IsNotExist(err) {
		t.Errorf("executeThemesPreview with absolute path should create file: %v", err)
	}
}

// TestExecuteThemesPreview_RelativePath tests with relative path
func TestExecuteThemesPreview_RelativePath(t *testing.T) {
	tmpDir := t.TempDir()
	originalDir, err := os.Getwd()
	if err != nil {
		t.Fatalf("failed to get current directory: %v", err)
	}

	if err := os.Chdir(tmpDir); err != nil {
		t.Fatalf("failed to change directory: %v", err)
	}
	defer func() { _ = os.Chdir(originalDir) }()

	relPath := "relative-preview.html"
	err = executeThemesPreview(relPath)
	if err != nil {
		t.Fatalf("executeThemesPreview with relative path returned error: %v", err)
	}

	// Verify file was created
	if _, err := os.Stat(relPath); os.IsNotExist(err) {
		t.Errorf("executeThemesPreview with relative path should create file: %v", err)
	}
}

// TestExecuteThemesPreview_FileSize tests that generated file has reasonable size
func TestExecuteThemesPreview_FileSize(t *testing.T) {
	tmpDir := t.TempDir()
	filePath := filepath.Join(tmpDir, "size-test.html")

	err := executeThemesPreview(filePath)
	if err != nil {
		t.Fatalf("executeThemesPreview returned error: %v", err)
	}

	info, err := os.Stat(filePath)
	if err != nil {
		t.Fatalf("failed to stat file: %v", err)
	}

	// File should be at least a few KB (should contain all themes and styles)
	if info.Size() < 1000 {
		t.Errorf("generated file should be at least 1KB, got %d bytes", info.Size())
	}

	// File should not be unreasonably large (should be less than 1MB)
	if info.Size() > 1000000 {
		t.Errorf("generated file should be less than 1MB, got %d bytes", info.Size())
	}
}

// TestGeneratePreviewHTML_ContainsViewportMeta tests responsive design meta tag
func TestGeneratePreviewHTML_ContainsViewportMeta(t *testing.T) {
	result := generatePreviewHTML([]Theme{})

	if !strings.Contains(result, `<meta name="viewport"`) {
		t.Error("generatePreviewHTML() should contain viewport meta tag for responsive design")
	}
}

// TestGeneratePreviewHTML_MediaQueries tests responsive design media queries
func TestGeneratePreviewHTML_MediaQueries(t *testing.T) {
	result := generatePreviewHTML([]Theme{})

	if !strings.Contains(result, "@media (max-width: 768px)") {
		t.Error("generatePreviewHTML() should contain media queries for responsive design")
	}
}

// TestGenerateThemePreviewSection_GradientHeader tests gradient header styling
func TestGenerateThemePreviewSection_GradientHeader(t *testing.T) {
	theme := Theme{
		Name:        "gradient",
		DisplayName: "Gradient Test",
		Description: "Testing gradient",
		Author:      "Tester",
		Version:     "1.0.0",
		Colors: ThemeColors{
			Primary:    "#667eea",
			Secondary:  "#764ba2",
			Accent:     "#999999",
			Text:       "#000000",
			Background: "#FFFFFF",
			CodeBg:     "#F0F0F0",
		},
	}

	result := generateThemePreviewSection(theme)

	// Verify gradient background is applied
	if !strings.Contains(result, "linear-gradient") {
		t.Error("generateThemePreviewSection() should apply gradient background to header")
	}
}

// TestGeneratePreviewHTML_ThemeInformation tests theme information section
func TestGeneratePreviewHTML_ThemeInformation(t *testing.T) {
	themes := []Theme{
		{
			Name:        "info",
			DisplayName: "Info Test",
			Description: "Description for info test",
			Author:      "Info Author",
			Version:     "1.2.3",
			Colors: ThemeColors{
				Primary:    "#000000",
				Secondary:  "#111111",
				Accent:     "#222222",
				Text:       "#333333",
				Background: "#FFFFFF",
				CodeBg:     "#F0F0F0",
			},
		},
	}

	result := generatePreviewHTML(themes)

	// Verify theme information is included
	if !strings.Contains(result, "theme-info") {
		t.Error("generatePreviewHTML() should include theme-info section")
	}
	if !strings.Contains(result, "Description for info test") {
		t.Error("generatePreviewHTML() should display theme description")
	}
}
