package cmd

import (
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/yeasy/mdpress/internal/theme"
)

// testThemeInfo returns a themeInfo backed by a live built-in theme.
func testThemeInfo(t *testing.T, name string) themeInfo {
	t.Helper()
	tm := theme.NewThemeManager()
	thm, err := tm.Get(name)
	if err != nil {
		t.Fatalf("failed to get theme %q: %v", name, err)
	}
	return newThemeInfo(thm)
}

// TestGeneratePreviewHTML_Basic tests basic HTML generation for themes preview
func TestGeneratePreviewHTML_Basic(t *testing.T) {
	themes := []themeInfo{testThemeInfo(t, "technical")}

	result := generatePreviewHTML(themes)

	// Verify HTML structure
	checks := []struct {
		name    string
		content string
	}{
		{"doctype", "<!DOCTYPE html>"},
		{"html lang", `<html lang="en">`},
		{"charset", `<meta charset="UTF-8">`},
		{"title", "<title>mdpress Themes Preview</title>"},
		{"header", "mdpress Theme Showcase"},
		{"container div", `<div class="container">`},
		{"themes grid", `<div class="themes-grid">`},
		{"footer", "Generated by mdpress"},
		{"closing html", "</html>"},
	}

	for _, check := range checks {
		if !strings.Contains(result, check.content) {
			t.Errorf("generatePreviewHTML() should contain %q, got output: %s", check.name, result[:200])
		}
	}
}

// TestGeneratePreviewHTML_EmptyThemes tests with no themes
func TestGeneratePreviewHTML_EmptyThemes(t *testing.T) {
	result := generatePreviewHTML([]themeInfo{})

	// Should still generate valid HTML structure
	if !strings.Contains(result, "<!DOCTYPE html>") {
		t.Error("generatePreviewHTML() should generate doctype even with empty themes")
	}
	if !strings.Contains(result, "mdpress Theme Showcase") {
		t.Error("generatePreviewHTML() should generate header even with empty themes")
	}
	if !strings.Contains(result, "</html>") {
		t.Error("generatePreviewHTML() should have closing html tag")
	}
}

// TestGeneratePreviewHTML_MultipleThemes tests with multiple themes
func TestGeneratePreviewHTML_MultipleThemes(t *testing.T) {
	themes := []themeInfo{
		testThemeInfo(t, "technical"),
		testThemeInfo(t, "elegant"),
	}

	result := generatePreviewHTML(themes)

	// Should contain both theme sections
	if !strings.Contains(result, "Technical") {
		t.Error("generatePreviewHTML() should contain first theme name")
	}
	if !strings.Contains(result, "Elegant") {
		t.Error("generatePreviewHTML() should contain second theme name")
	}
}

// TestGeneratePreviewHTML_RendersLivePalette is the anti-desync regression
// guard for the preview: the generated page must embed the current builtin
// palette values from internal/theme, not a stale hardcoded copy.
func TestGeneratePreviewHTML_RendersLivePalette(t *testing.T) {
	tm := theme.NewThemeManager()

	result := generatePreviewHTML(getAvailableThemes())

	for _, name := range tm.List() {
		live, err := tm.Get(name)
		if err != nil {
			t.Fatalf("failed to get theme %q: %v", name, err)
		}
		for field, value := range map[string]string{
			"heading":    live.Colors.Heading,
			"link":       live.Colors.Link,
			"accent":     live.Colors.Accent,
			"background": live.Colors.Background,
			"code bg":    live.Colors.CodeBg,
		} {
			if !strings.Contains(result, value) {
				t.Errorf("preview should contain theme %q live %s color %q", name, field, value)
			}
		}
	}

	// Stale pre-v0.7.13 palette values must not resurface.
	for _, stale := range []string{"#1A5490", "#0066CC", "#2C3E50", "#ecf0f1", "#d35400"} {
		if strings.Contains(result, stale) {
			t.Errorf("preview contains stale pre-v0.7.13 palette value %q", stale)
		}
	}
}

// TestGeneratePreviewHTML_ContainsStyles tests that CSS styles are present
func TestGeneratePreviewHTML_ContainsStyles(t *testing.T) {
	themes := []themeInfo{}
	result := generatePreviewHTML(themes)

	styleChecks := []string{
		"<style>",
		"</style>",
		"body {",
		"font-family:",
		"background:",
		".container {",
		".themes-grid {",
		".theme-section {",
		"@media",
	}

	for _, check := range styleChecks {
		if !strings.Contains(result, check) {
			t.Errorf("generatePreviewHTML() should contain CSS %q", check)
		}
	}
}

// TestGeneratePreviewHTML_ValidHTML tests that generated HTML is well-formed
func TestGeneratePreviewHTML_ValidHTML(t *testing.T) {
	themes := []themeInfo{testThemeInfo(t, "minimal")}

	result := generatePreviewHTML(themes)

	// Check opening and closing tags match. The samples are embedded via
	// escaped srcdoc attributes, so raw tag counts only cover the outer page.
	htmlOpen := strings.Count(result, "<html")
	htmlClose := strings.Count(result, "</html>")
	if htmlOpen != htmlClose {
		t.Error("generatePreviewHTML() html tags should match")
	}

	bodyOpen := strings.Count(result, "<body")
	bodyClose := strings.Count(result, "</body>")
	if bodyOpen != bodyClose {
		t.Error("generatePreviewHTML() body tags should match")
	}

	headOpen := strings.Count(result, "<head")
	headClose := strings.Count(result, "</head>")
	if headOpen != headClose {
		t.Error("generatePreviewHTML() head tags should match")
	}
}

// TestGenerateThemePreviewSection_Basic tests single theme section generation
func TestGenerateThemePreviewSection_Basic(t *testing.T) {
	info := testThemeInfo(t, "technical")

	result := generateThemePreviewSection(info)

	// Verify structure
	if !strings.Contains(result, "theme-section") {
		t.Error("generateThemePreviewSection() should contain theme-section class")
	}
	if !strings.Contains(result, "Technical") {
		t.Error("generateThemePreviewSection() should contain display name")
	}
	if !strings.Contains(result, "technical") {
		t.Error("generateThemePreviewSection() should contain theme name")
	}
	if !strings.Contains(result, "(default)") {
		t.Error("generateThemePreviewSection() should mark the default theme")
	}
}

// TestGenerateThemePreviewSection_ContainsColors tests color swatch display
func TestGenerateThemePreviewSection_ContainsColors(t *testing.T) {
	info := testThemeInfo(t, "elegant")

	result := generateThemePreviewSection(info)

	// Verify all live palette values and swatch labels are included
	colorChecks := []string{
		info.colors.primary,
		info.colors.secondary,
		info.colors.accent,
		info.colors.text,
		info.colors.background,
		info.colors.codeBg,
		info.colors.codeText,
		info.colors.border,
		"color-swatch",
		"Heading",
		"Link",
		"Accent",
		"Background",
	}

	for _, check := range colorChecks {
		if !strings.Contains(result, check) {
			t.Errorf("generateThemePreviewSection() should contain %q", check)
		}
	}
}

// TestGenerateThemePreviewSection_EmbedsSampleIframe tests that the sample is
// embedded as a srcdoc iframe carrying the theme's real stylesheet.
func TestGenerateThemePreviewSection_EmbedsSampleIframe(t *testing.T) {
	info := testThemeInfo(t, "technical")

	result := generateThemePreviewSection(info)

	checks := []string{
		`class="theme-sample"`,
		`srcdoc="`,
		// Escaped inner document markers.
		"&lt;!DOCTYPE html&gt;",
		// ToCSS variables survive escaping verbatim (no <>&" characters).
		"--color-heading: " + info.theme.Colors.Heading,
		"--color-link: " + info.theme.Colors.Link,
		// v0.7.13 pipeline rules: zebra striping and header accent underline.
		// Match the var() reference without its closing paren so an optional
		// fallback value, e.g. var(--color-accent, #1C5A9E), also passes.
		"table tbody tr:nth-child(even) td",
		"border-bottom: 2px solid var(--color-accent",
	}
	for _, check := range checks {
		if !strings.Contains(result, check) {
			t.Errorf("generateThemePreviewSection() should contain %q", check)
		}
	}
}

// TestThemeSampleDocument_UsesRealPipelineCSS verifies that the per-theme
// sample document is styled by theme.ToCSS() and contains a representative
// content sample (headings, table with header+zebra, code, blockquote, link).
func TestThemeSampleDocument_UsesRealPipelineCSS(t *testing.T) {
	info := testThemeInfo(t, "technical")

	doc := themeSampleDocument(info)

	// The full pipeline stylesheet must be embedded verbatim.
	if !strings.Contains(doc, info.theme.ToCSS()) {
		t.Fatal("sample document should embed the theme's ToCSS() output verbatim")
	}

	contentChecks := []string{
		"<h1>Sample Heading</h1>",
		"<h2>Section Heading</h2>",
		"sample paragraph",
		`<a href="#">sample link</a>`,
		"<code>inline code</code>",
		"Sample code block",
		"func greet",
		"<table>",
		"<thead>",
		"<tbody>",
		"<blockquote>",
		"Feature",
		"Value",
	}
	for _, check := range contentChecks {
		if !strings.Contains(doc, check) {
			t.Errorf("themeSampleDocument() should contain %q", check)
		}
	}

	// The table needs at least four body rows so zebra striping is visible.
	if got := strings.Count(doc, "<tr><td>"); got < 4 {
		t.Errorf("sample table should have at least 4 body rows for zebra striping, got %d", got)
	}
}

// TestThemeSampleDocument_NilTheme verifies a nil live theme does not panic.
func TestThemeSampleDocument_NilTheme(t *testing.T) {
	doc := themeSampleDocument(themeInfo{name: "broken"})
	if !strings.Contains(doc, "<h1>Sample Heading</h1>") {
		t.Error("sample document should render content even without a live theme")
	}
}

// TestExecuteThemesPreview_DefaultPath tests preview generation with default path
func TestExecuteThemesPreview_DefaultPath(t *testing.T) {
	defer suppressOutput(t)()
	tmpDir := t.TempDir()
	t.Chdir(tmpDir)

	err := executeThemesPreview("")
	if err != nil {
		t.Fatalf("executeThemesPreview(\"\") returned error: %v", err)
	}

	// Verify file was created with default name
	if _, err := os.Stat("themes-preview.html"); errors.Is(err, fs.ErrNotExist) {
		t.Error("executeThemesPreview(\"\") should create themes-preview.html")
	}
}

// TestExecuteThemesPreview_CustomPath tests preview generation with custom path
func TestExecuteThemesPreview_CustomPath(t *testing.T) {
	defer suppressOutput(t)()
	tmpDir := t.TempDir()
	customPath := filepath.Join(tmpDir, "custom-preview.html")

	err := executeThemesPreview(customPath)
	if err != nil {
		t.Fatalf("executeThemesPreview with custom path returned error: %v", err)
	}

	// Verify file was created at custom path
	if _, err := os.Stat(customPath); errors.Is(err, fs.ErrNotExist) {
		t.Errorf("executeThemesPreview(%q) should create file at custom path", customPath)
	}
}

// TestExecuteThemesPreview_CreatesValidHTML tests that generated file contains valid HTML
func TestExecuteThemesPreview_CreatesValidHTML(t *testing.T) {
	defer suppressOutput(t)()
	tmpDir := t.TempDir()
	filePath := filepath.Join(tmpDir, "test-preview.html")

	err := executeThemesPreview(filePath)
	if err != nil {
		t.Fatalf("executeThemesPreview returned error: %v", err)
	}

	// Read the generated file
	content, err := os.ReadFile(filePath)
	if err != nil {
		t.Fatalf("failed to read generated file: %v", err)
	}

	contentStr := string(content)

	// Verify it contains valid HTML
	if !strings.Contains(contentStr, "<!DOCTYPE html>") {
		t.Error("generated file should contain DOCTYPE")
	}
	if !strings.Contains(contentStr, "mdpress Theme Showcase") {
		t.Error("generated file should contain theme showcase header")
	}
	if !strings.Contains(contentStr, "</html>") {
		t.Error("generated file should have closing html tag")
	}
}

// TestExecuteThemesPreview_QuietSuppressesStatus verifies --quiet silences
// the status line while still writing the preview file.
func TestExecuteThemesPreview_QuietSuppressesStatus(t *testing.T) {
	tmpDir := t.TempDir()
	filePath := filepath.Join(tmpDir, "quiet-preview.html")

	prevQuiet := quiet
	defer func() { quiet = prevQuiet }()

	quiet = true
	out, err := captureThemesStdout(t, func() error {
		return executeThemesPreview(filePath)
	})
	if err != nil {
		t.Fatalf("executeThemesPreview returned error: %v", err)
	}
	if strings.Contains(out, "Theme preview generated") {
		t.Errorf("quiet mode should suppress the status line, got: %q", out)
	}
	if _, statErr := os.Stat(filePath); statErr != nil {
		t.Errorf("preview file should still be written in quiet mode: %v", statErr)
	}

	quiet = false
	out, err = captureThemesStdout(t, func() error {
		return executeThemesPreview(filepath.Join(tmpDir, "loud-preview.html"))
	})
	if err != nil {
		t.Fatalf("executeThemesPreview returned error: %v", err)
	}
	if !strings.Contains(out, "Theme preview generated") {
		t.Errorf("non-quiet mode should print the status line, got: %q", out)
	}
}

// TestExecuteThemesPreview_FilePermissions tests that generated file has correct permissions
func TestExecuteThemesPreview_FilePermissions(t *testing.T) {
	defer suppressOutput(t)()
	tmpDir := t.TempDir()
	filePath := filepath.Join(tmpDir, "perm-test.html")

	err := executeThemesPreview(filePath)
	if err != nil {
		t.Fatalf("executeThemesPreview returned error: %v", err)
	}

	// Check file exists and is readable
	info, err := os.Stat(filePath)
	if err != nil {
		t.Fatalf("failed to stat generated file: %v", err)
	}

	if !info.Mode().IsRegular() {
		t.Error("generated file should be a regular file")
	}

	// Verify we can read the file
	_, err = os.ReadFile(filePath)
	if err != nil {
		t.Errorf("should be able to read generated file: %v", err)
	}
}

// TestExecuteThemesPreview_AbsolutePath tests with absolute path
func TestExecuteThemesPreview_AbsolutePath(t *testing.T) {
	defer suppressOutput(t)()
	tmpDir := t.TempDir()
	absPath := filepath.Join(tmpDir, "absolute-preview.html")

	err := executeThemesPreview(absPath)
	if err != nil {
		t.Fatalf("executeThemesPreview with absolute path returned error: %v", err)
	}

	// Verify file was created
	if _, err := os.Stat(absPath); errors.Is(err, fs.ErrNotExist) {
		t.Errorf("executeThemesPreview with absolute path should create file: %v", err)
	}
}

// TestExecuteThemesPreview_RelativePath tests with relative path
func TestExecuteThemesPreview_RelativePath(t *testing.T) {
	defer suppressOutput(t)()
	tmpDir := t.TempDir()
	t.Chdir(tmpDir)

	relPath := "relative-preview.html"
	err := executeThemesPreview(relPath)
	if err != nil {
		t.Fatalf("executeThemesPreview with relative path returned error: %v", err)
	}

	// Verify file was created
	if _, err := os.Stat(relPath); errors.Is(err, fs.ErrNotExist) {
		t.Errorf("executeThemesPreview with relative path should create file: %v", err)
	}
}

// TestExecuteThemesPreview_FileSize tests that generated file has reasonable size
func TestExecuteThemesPreview_FileSize(t *testing.T) {
	defer suppressOutput(t)()
	tmpDir := t.TempDir()
	filePath := filepath.Join(tmpDir, "size-test.html")

	err := executeThemesPreview(filePath)
	if err != nil {
		t.Fatalf("executeThemesPreview returned error: %v", err)
	}

	info, err := os.Stat(filePath)
	if err != nil {
		t.Fatalf("failed to stat file: %v", err)
	}

	// File should be at least a few KB (should contain all themes and styles)
	if info.Size() < 1000 {
		t.Errorf("generated file should be at least 1KB, got %d bytes", info.Size())
	}

	// File should not be unreasonably large (should be less than 1MB)
	if info.Size() > 1000000 {
		t.Errorf("generated file should be less than 1MB, got %d bytes", info.Size())
	}
}

// TestGeneratePreviewHTML_ContainsViewportMeta tests responsive design meta tag
func TestGeneratePreviewHTML_ContainsViewportMeta(t *testing.T) {
	result := generatePreviewHTML([]themeInfo{})

	if !strings.Contains(result, `<meta name="viewport"`) {
		t.Error("generatePreviewHTML() should contain viewport meta tag for responsive design")
	}
}

// TestGeneratePreviewHTML_MediaQueries tests responsive design media queries
func TestGeneratePreviewHTML_MediaQueries(t *testing.T) {
	result := generatePreviewHTML([]themeInfo{})

	if !strings.Contains(result, "@media (max-width: 768px)") {
		t.Error("generatePreviewHTML() should contain media queries for responsive design")
	}
}

// TestGenerateThemePreviewSection_GradientHeader tests gradient header styling
func TestGenerateThemePreviewSection_GradientHeader(t *testing.T) {
	info := testThemeInfo(t, "minimal")

	result := generateThemePreviewSection(info)

	// Verify gradient background is applied
	if !strings.Contains(result, "linear-gradient") {
		t.Error("generateThemePreviewSection() should apply gradient background to header")
	}
}

// TestGeneratePreviewHTML_ThemeInformation tests theme information section
func TestGeneratePreviewHTML_ThemeInformation(t *testing.T) {
	info := testThemeInfo(t, "elegant")

	result := generatePreviewHTML([]themeInfo{info})

	// Verify theme information is included
	if !strings.Contains(result, "theme-info") {
		t.Error("generatePreviewHTML() should include theme-info section")
	}
	if !strings.Contains(result, info.description) {
		t.Error("generatePreviewHTML() should display theme description")
	}
}
